### ISSUE TITLE
A question about how to verify the facts  by GPT-J 

### ISSUE THREAD

**Issue by wtma1999** [Arvid-pku/ATOKE#3]
Hi !
I hope this message finds you well. I was reviewing the ATOKE on GitHub. I appreciate the effort you've put into this, but I have a few questions for clarification.

In your article, during constructing the benchmark, GPT-J is used to verify whether the facts model has. I have some questions about this. Are you directly verifying the decoded results with the original answers, or are you filtering through the probability set threshold of the decoded results. In addition, how is the verification of the original answer non-sing-token completed?

I'm eager to understand this better. Your assistance would be greatly appreciated.

Thank you for your time and consideration.

**Comment by Arvid-pku** [comment]
Thank for your attention and sorry for the late reply!
we use the exact match to filter the knowledge. (We perform string matching in the generated text of LLMs, even for multi-token answer.)
